### ISSUE TITLE
Facebook app settings

### ISSUE THREAD

**Issue by iampilchards** [leozachl/dokuwiki-authfacebook#1]
Hi

In your install instructions, please include what the settings should be for the Security section, especially the "Valid OAuth redirect URIs"

Thanks

**Comment by leozachl** [comment]
this is usually your dokuwiki url.
if you use your facebook app for more than one site,
enter a list of all valid URIs.
only these URIs will be accepted by https://www.facebook.com/dialog/oauth as redirect_uri parameter
