### ISSUE TITLE
Possible to add login button everywhere?

### ISSUE THREAD

**Issue by robertrosman** [leozachl/dokuwiki-authfacebook#3]
I'd ideally like to skip the login page, but instead be sent to the facebook login page directly when clicking the login button. Is it possible, or do one have to go via the do=login page?

**Comment by leozachl** [comment]
don't know if there is a correct dokuwiki way to do this.
but you can call
trigger_event('HTML_LOGINFORM_OUTPUT',$evdata);
at the USER TOOLS section in your template, reformat it and hide text via css,
or copy the code from plugins/authfacebook/action.php:49
but hide it when the user is logged in.

**Comment by robertrosman** [comment]
Cool, thanks for the tip!
