### ISSUE TITLE
Permissions needed

### ISSUE THREAD

**Issue by lewinschmitt** [leozachl/dokuwiki-authfacebook#4]
It seems like the app also needs permissions to read the user's groups and stream, which I don't consider relevant for my use case. Whenever I try to login to dokuwiki via authfacebook, it forwards me to facebook, when a red alert message pops up saying:

"Invalid Scopes: user_groups, read_stream. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions"

is there any way I can avoid this? Thanks a lot in advance!

**Comment by lewinschmitt** [comment]
Ok, manually editing the config file and deleting user_groups and read_stream from the scopes entry did the trick.

the corresponding line in local.php has to look like this (maybe you have to add it):
$conf['plugin']['authfacebook']['scope'] = ' ';

However, facebook users that login via the script now don't show up in my user management, which is kinda annoying.

**Comment by leozachl** [comment]
The requeseted permissions/scope is now configurable
