### ISSUE TITLE
$_SERVER['REMOTE_USER'] is invalid facebook id

### ISSUE THREAD

**Issue by robertrosman** [leozachl/dokuwiki-authfacebook#6]
For some reason the id used by dokuwiki isn't the same as the facebook id. I understand that Facebook deprecated the username, but it's not the numerical id either, but rather a shortened version of the email. Is there any other variable I can use to get the fb id? I need it to display the correct profile picture.

**Comment by leozachl** [comment]
with version ?? facebook uses per app ids.
to get the profile photo use the api call:
https://developers.facebook.com/docs/graph-api/reference/user/picture/
